### PR TITLE
Update version to 1.0.1-RC

### PR DESCRIPTION
**Pull request by PenghaiZhang**

### CODE REVIEW

**Comment by PenghaiZhang** [comment]
Just note that I did a force push because I rebased this branch onto Develop in order to include the feature of publishing build results to Github Release via Travis.

**Comment by edalex-ian** [comment]
So, you'd normally want your release branch targetting `master`. Did you want to change that?

And, I assume you're also going to tag this branch to trigger an RC publish?

**Comment by PenghaiZhang** [comment]
> So, you'd normally want your release branch targetting `master`. Did you want to change that?
> 
> And, I assume you're also going to tag this branch to trigger an RC publish?

Thanks @edalex-ian reminding me that I should have targeted `master`.

Yes I want to create a new tag and see if Travis can do the publish work well

**Comment by PenghaiZhang** [comment]
Finally got a green build triggered by a tag and this build publish artifacts to Github Release. But I don't understand why those failed builds also published artifacts to Github Release.

**Comment by PenghaiZhang** [comment]
Hi @edalex-ian , when you get a chance, shall we update the credentials as they are currently generated from my personal account ? Also could you please have a look the last commit ?

**Comment by edalex-ian** [comment]
> Hi @edalex-ian , when you get a chance, shall we update the credentials as they are currently generated from my personal account ? Also could you please have a look the last commit ?

Looks about right to me - I vaguely remember doing such in batch scripts way back when I last did them... :) And I see testing was successful, so that's promising.

As for creds, we can organise that.

**Pull request merged**
