### PR TITLE
OEQ-1584 - chore: add more size of icon to enhance adaptability

### PR DESCRIPTION
**Pull request by edalex-yinzi**
Add more size of icon to enhance adaptability according to this [article](https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction)

32px:
image

48px:

image

68px:

image

48px and 64 looks good, but for 32px,  compared with the work down for the admin connsole jar in GitLab (MR 257) here looks more pixelated.

### CODE REVIEW

**Comment by edalex-ian** [comment]
Two things:

1. Screenshots please; and
2. That link you provided is pointing to the Bb project - not a guide.

**Comment by edalex-yinzi** [comment]
Cool! Thanks, Ian. I have updated the description.

**Comment by edalex-ian** [comment]
That's curious. It's as though it hasn't actually used the 32px image, and instead downscaled one of the others. :thinking:

**Review by edalex-ian — APPROVED** [review]
Although there's the weird 32px issue, I think it should be fine. So let's merge this in and see what is found in testing. (Make sure you update the link in the testing notes in Jira.)

/approve

**Comment by edalex-yinzi** [comment]
> Although there's the weird 32px issue, I think it should be fine. So let's merge this in and see what is found in testing. (Make sure you update the link in the testing notes in Jira.)
> 
> /approve

OK.

**Comment by edalex-yinzi** [comment]
I dont have permission. You can merge it. :wink:

**Pull request merged**
